name: Build and release Windows packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache cargo registry & src-tauri target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install WiX Toolset (required for MSI builds)
        run: choco install wixtoolset -y

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
          target: x86_64-pc-windows-msvc

      - name: Install JS dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Build Tauri Windows package(s)
        run: npx tauri build --target msi
        working-directory: .

      - name: Create GitHub Release and upload Windows artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          files: |
            src-tauri/target/release/bundle/windows/*.msi
            src-tauri/target/release/bundle/windows/*.exe